openapi: 3.0.0
info:
    title: Raidiam Connect
    description: Raidiam Connect API
    contact:
        email: support@raidiam.com
    license:
        name: MIT
        url: https://mit-license.org
    version: 1.20.1
tags:
    - description: all operations relating to users
      name: Users
    - description: all operations relating to software statement certifications
      name: Software Statement Certifications
    - description: all operations relating to certification managers
      name: Certification Managers
    - description: all operations relating to super users
      name: Super Users
    - description: all operations relating to organisation admins
      name: Organisation Admin Users
    - description: all operations relating to organisation domain users
      name: Organisation Domain Users
    - description: all operations utilising docusign
      name: Docusign
    - description: all operations relating to organisations
      name: Organisations
    - description: all operations relating to data export
      name: Export
    - description: all operations relating to the participants endpoint
      name: Participants
    - description: all operations relating to directory roles
      name: Roles
    - description: all depreciated operations
      name: Deprecated
    - description: all operations involving the conformance suite
      name: Conformance Suite
    - description: all operations relating to reference data
      name: Reference Data
    - description: all operations relating to authorities
      name: Authorities
    - description: all operations relating to authorisation domains
      name: Authorisation Domains
    - description: all operations relating to authorisation domain roles
      name: Authorisation Domain Roles
    - description: all operations relating to authorisation domain role metadata
      name: Authorisation Domain Role Metadata
    - description: all operations relating to the mapping between authorities and authorisation domains
      name: Authority Domain Mappings
    - description: all operations relating to directory terms and conditions
      name: Terms and Conditions
    - description: all operations relating to authority domain claims attached to an organisation
      name: Authority Domain Claims
    - description: all operations relating to roles attached to an organisation
      name: Authority Claims
    - description: all operations relating to authority claim authorisations
      name: Authority Claims Authorisations
    - description: all operations relating to contacts
      name: Contacts
    - description: all operations relating to authorisation servers
      name: Authorisation Servers
    - description: all operations relating to webhooks
      name: Webhooks
    - description: all operations relating to api resources
      name: API Resources
    - description: all operations relating to api discovery endpoints listed on an api resource
      name: API Discovery Endpoints
    - description: all operations relating to the certifying of a directory resource
      name: Certifications
    - description: all operations relating to software statements
      name: Software Statements
    - description: all operations relating to authority claims attached to a software statement
      name: Software Authority Claims
    - description: all operations relating to certificates
      name: Certificates
    - description: all operations relating to the software statement assertion
      name: Assertion
    - description: all operations relating to software statement metadata
      name: Software Statement Metadata
    - description: all operations relating to the openid provider
      name: OpenID Provider
    - description: all operations relating to the clients endpoint
      name: Client Registration
    - description: all operations relating to fetching audit history
      name: Audit History
    - description: all operations relating to federation
      name: Federation
    - description: all operations relating to organisation labels inside reference data
      name: Organisation Label
    - description: all operations relating to certification types
      name: Certification Type
    - description: all operations relating to certification type variants
      name: Certification Type Variant
    - description: all endpoints to be included in the public api documentation
      name: Public
    - description: endpoints for the super user dashboard
      name: Dashboard
    - description: all endpoints to be included in the closed api documentation
      name: Closed
    - description: all endpoints relating to resource flags
      name: Flags
servers:
    - url: https://matls-api.sandbox.raidiam.io
      description: Raidiam Directory Sandbox Environment

paths:
  '/audit':
    get:
      summary: Fetches audit history based on query parameters
      tags:
        - Audit History
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/clients':
    get:
      summary: Get all registered clients
      tags:
        - Software Statements
        - Client Registration
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Refresh/rebuild the registered clients data
      tags:
        - Software Statements
        - Client Registration
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/clients/{ClientId}':
    get:
      summary: Get details for one client
      tags:
        - Software Statements
        - Client Registration
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations':
    get:
      summary: Get all organisations that the logged in user is authorised to retrieve from trusted services
      tags:
        - Organisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post a new organisation in the directory.
      tags:
        - Organisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}':
    get:
      summary: Get the given organisations details
      tags:
        - Organisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Amend the given organisations details
      tags:
        - Organisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete an organisation by changing its status to "Withdrawn"
      tags:
        - Organisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/adminusers':
    get:
      summary: All admin users for the given organisation
      tags:
        - Users
        - Organisation Admin Users
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:servicedesk
      
    post:
      summary: Create an organisation admin user
      tags:
        - Users
        - Organisation Admin Users
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/adminusers/{UserEmailId}':
    get:
      summary: Gets details of an organisation admin user by their email address
      tags:
        - Users
        - Organisation Admin Users
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:servicedesk
      
    put:
      summary: reactivate or deactivate an organisation admin user by their email address
      tags:
        - Users
        - Organisation Admin Users
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers':
    get:
      summary: Get all Authorisation Servers for the given organisation
      tags:
        - Organisations
        - Authorisation Servers
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create an Authorisation Server for the given organisation
      tags:
        - Organisations
        - Authorisation Servers
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}':
    get:
      summary: Get an authorisation server by Id
      tags:
        - Organisations
        - Authorisation Servers
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an authorisation server
      tags:
        - Organisations
        - Authorisation Servers
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete an Authorisation Server
      tags:
        - Organisations
        - Authorisation Servers
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/apiresources':
    get:
      summary: Get all Api Resources for the given Authorisation Server
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create an Api Resource for the given organisation and Authorisation Server
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/apiresources/{ApiResourceId}':
    get:
      summary: Get an authorisation server API resource by Id
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an Api Resource for the given organisation and Authorisation Server
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete an authorisation server API resource by Id
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/apiresources/{ApiResourceId}/apidiscoveryendpoints':
    get:
      summary: Get all Api Discovery Endpoints for the given Authorisation Server and Api Version
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - API Discovery Endpoints
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create an Api Discovery Endpoint for the given organisation and Authorisation Server and Api Version
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - API Discovery Endpoints
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/apiresources/{ApiResourceId}/apidiscoveryendpoints/{ApiDiscoveryEndpointId}':
    get:
      summary: Get an authorisation server API discovery endpoint by Id
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - API Discovery Endpoints
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an Api Discovery Endpoint for the given organisation, Authorisation Server and Api Version
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - API Discovery Endpoints
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete an Api Discovery Endpoint for the given organisation, Authorisation Server and Api Version
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - API Discovery Endpoints
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/certifications':
    get:
      summary: Get all certifications for given authorisation server
      tags:
        - Organisations
        - Authorisation Servers
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post a certification for the given authorisation server
      tags:
        - Organisations
        - Authorisation Servers
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/certifications/{AuthorisationServerCertificationId}':
    get:
      summary: Get a certification by Id
      tags:
        - Organisations
        - Authorisation Servers
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update the given certification
      tags:
        - Organisations
        - Authorisation Servers
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Remove a certification with the given certification Id
      tags:
        - Organisations
        - Authorisation Servers
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/familystatus':
    get:
      summary: Get an authorisation server API resource by Id and returns the latest family status
      tags:
        - Organisations
        - Authorisation Servers
        - API Resources
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/federation':
    get:
      summary: Get all authorisation server federation configuration by Authorisation Server Id
      tags:
        - Organisations
        - Authorisation Servers
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create an authorisation server federation configuration
      tags:
        - Organisations
        - Authorisation Servers
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorisationservers/{AuthorisationServerId}/federation/{FederationConfigId}':
    get:
      summary: Get an authorisation server federation configuration by Federation Config Id
      tags:
        - Organisations
        - Authorisation Servers
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update the status of a given Federation configuration
      tags:
        - Organisations
        - Authorisation Servers
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete an Authorisation Server Federation Configuration
      tags:
        - Organisations
        - Authorisation Servers
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorityclaims':
    get:
      summary: Get the authority claims for the given organisation
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post an authority claim
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorityclaims/{OrganisationAuthorityClaimId}':
    get:
      summary: Get an authority claim by Id
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an authority claim for the given Id
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete an authority claim
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorityclaims/{OrganisationAuthorityClaimId}/authorisations':
    get:
      summary: Get an authority claims authorisations
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Authority Claims Authorisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post an authority claims authorisations
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Authority Claims Authorisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authorityclaims/{OrganisationAuthorityClaimId}/authorisations/{OrganisationAuthorisationId}':
    get:
      summary: Get a claim authorisation
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Authority Claims Authorisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    delete:
      summary: Remove an authorisation from authority claims
      tags:
        - Organisations
        - Authority Claims
        - Authority Domain Claims
        - Authorisation Domain Roles
        - Authorisation Domains
        - Authorities
        - Authority Claims Authorisations
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authoritydomainclaims':
    get:
      summary: Get the authority domain claims for the given organisation
      tags:
        - Organisations
        - Authority Domain Claims
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post an authority domain claim
      tags:
        - Organisations
        - Authority Domain Claims
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/authoritydomainclaims/{OrganisationAuthorityDomainClaimId}':
    get:
      summary: Get an authority domain claim by Id
      tags:
        - Organisations
        - Authority Domain Claims
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an authority domain claim by Id
      tags:
        - Organisations
        - Authority Domain Claims
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Deactivate an authority domain claim by Id
      tags:
        - Organisations
        - Authority Domain Claims
        - Authorisation Domains
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/certificates':
    get:
      summary: Get the certificates for the given organisation
      tags:
        - Organisations
        - Certificates
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/certificates/kid/{CertificateOrKeyId}':
    get:
      summary: Retrieve a certificate with the given CertificateOrKeyId
      tags:
        - Organisations
        - Certificates
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Revoke or remove a certificate with the given CertificateOrKeyId providing a revoke reason
      tags:
        - Organisations
        - Certificates
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/certificates/{OrganisationCertificateType}':
    get:
      summary: Get the certificates of the given OrganisationCertificateType for the given organisation
      tags:
        - Organisations
        - Certificates
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Store or create a new certificate of the given OrganisationCertificateType for the given organisation
      tags:
        - Organisations
        - Certificates
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/conformancetest':
    post:
      summary: Create and execute a Conformance Suite test plan for the given organisation
      tags:
        - Organisations
        - Conformance Suite
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/contacts':
    get:
      summary: Get the contacts for the given organisation
      tags:
        - Organisations
        - Contacts
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post a contact for the given organisation
      tags:
        - Organisations
        - Contacts
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/contacts/{ContactId}':
    get:
      summary: Get a contact by Id
      tags:
        - Organisations
        - Contacts
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update the contacts for the given organisation
      tags:
        - Organisations
        - Contacts
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Remove a contact in an organisation with the given contact id
      tags:
        - Organisations
        - Contacts
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/ess/initiatesigning':
    post:
      summary: This API initiates ESS signing process by an org admin
      tags:
        - Organisations
        - Docusign
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/ess/reissue/{ExternalSigningServiceEnvelopeId}':
    post:
      summary: This API marks the current envelope as reissued and allows a new one to be started
      tags:
        - Organisations
        - Docusign
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/softwarestatements':
    get:
      summary: Get all software statements for the given organisation
      tags:
        - Organisations
        - Software Statements
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create a software statement
      tags:
        - Organisations
        - Software Statements
        - OpenID Provider
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}':
    get:
      summary: Get a specific software statement
      tags:
        - Organisations
        - Software Statements
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update a software statement by Id.
      tags:
        - Organisations
        - Software Statements
        - OpenID Provider
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    delete:
      summary: Delete or revoke a software statement with the given softwarestatementID
      tags:
        - Organisations
        - Software Statements
        - OpenID Provider
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/assertion':
    get:
      summary: Get a Software Statement Assertion for the given SoftwareStatementID.
      tags:
        - Organisations
        - Software Statements
        - Assertion
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/authorityclaims':
    get:
      summary: Get the authority claims for the given software statement
      tags:
        - Organisations
        - Software Statements
        - Authority Claims
        - Software Authority Claims
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post an authority claim for a software statement
      tags:
        - Organisations
        - Software Statements
        - Authority Claims
        - Software Authority Claims
        - OpenID Provider
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/authorityclaims/{SoftwareAuthorityClaimId}':
    get:
      summary: Get an authority claim by Id
      tags:
        - Organisations
        - Software Statements
        - Authority Claims
        - Software Authority Claims
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an authority claim for the given Id
      tags:
        - Organisations
        - Software Statements
        - Authority Claims
        - Software Authority Claims
        - OpenID Provider
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/certificates':
    get:
      summary: Get certificates for the given software statement
      tags:
        - Organisations
        - Software Statements
        - Certificates
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/certificates/{SoftwareStatementCertificateOrKeyType}':
    post:
      summary: Add a key or create a new certificate for the given software statement
      tags:
        - Organisations
        - Software Statements
        - Certificates
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/certificates/{SoftwareStatementCertificateOrKeyType}/{CertificateOrKeyId}':
    get:
      summary: Get the certificate of the given type and ID for the given software statement
      tags:
        - Organisations
        - Software Statements
        - Certificates
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update a software statement certificate with the given CertificateOrKeyId e.g. revoke reason
      tags:
        - Organisations
        - Software Statements
        - Certificates
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/certifications':
    get:
      summary: Get all certifications for given Software Statement.
      tags:
        - Organisations
        - Software Statements
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Post a certification for the given Software Statement
      tags:
        - Organisations
        - Software Statements
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/certifications/{SoftwareStatementCertificationId}':
    get:
      summary: Get a certification by Id
      tags:
        - Organisations
        - Software Statements
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update the given certification
      tags:
        - Organisations
        - Software Statements
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Remove a certification with the given certification Id
      tags:
        - Organisations
        - Software Statements
        - Certifications
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/metadata':
    get:
      summary: Get all metadata associated with a software statement
      tags:
        - Organisations
        - Software Statements
        - Authority Claims
        - Authorisation Domain Role Metadata
        - Software Statement Metadata
        - Public
        - Closed
      security:
        - oAuth:
          - directory:software
          - directory:website
      
  '/organisations/{OrganisationId}/softwarestatements/{SoftwareStatementId}/unlock':
    put:
      summary: Unlock a software statement.
      tags:
        - Organisations
        - Software Statements
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/tnchistory':
    get:
      summary: Get all TnC data of the given organisation
      tags:
        - Organisations
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/{AuthorisationDomainName}/users':
    get:
      summary: All users for the given authorisation domain
      tags:
        - Users
        - Organisation Domain Users
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
          - directory:servicedesk
      
    post:
      summary: Create an authorisation domain user
      tags:
        - Users
        - Organisation Domain Users
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/organisations/{OrganisationId}/{AuthorisationDomainName}/users/{UserEmailId}':
    get:
      summary: Authorisation Domain user details
      tags:
        - Users
        - Organisation Domain Users
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
          - directory:servicedesk
      
  '/organisations/{OrganisationId}/{AuthorisationDomainName}/users/{UserEmailId}/{AuthorisationDomainUserId}':
    put:
      summary: Update an authorisation domain user record by the unique identifier
      tags:
        - Public
        - Users
        - Organisation Domain Users
      security:
        - oAuth:
          - directory:website
      
  '/references/authorisationdomainroles':
    get:
      summary: Reference data of all authorisation domain roles
      tags:
        - Reference Data
        - Authorisation Domain Roles
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create an authorisation domain role
      tags:
        - Reference Data
        - Authorisation Domain Roles
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorisationdomainroles/{AuthorisationDomainRoleName}':
    get:
      summary: Get an authorisation domain role by name
      tags:
        - Reference Data
        - Authorisation Domain Roles
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an authorisation domain role by name
      tags:
        - Reference Data
        - Authorisation Domain Roles
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Deactivate an authorisation domain role by Name
      tags:
        - Reference Data
        - Authorisation Domain Roles
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorisationdomainroles/{AuthorisationDomainRoleName}/metadata':
    get:
      summary: Get metadata associated with an authorisation domain role
      tags:
        - Reference Data
        - Authorisation Domain Role Metadata
        - Public
        - Closed
      security:
        - oAuth:
          - directory:software
          - directory:website
      
    post:
      summary: Create a metadata record associated with an authorisation domain role
      tags:
        - Reference Data
        - Authorisation Domain Role Metadata
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorisationdomainroles/{AuthorisationDomainRoleName}/metadata/{MetadataId}':
    get:
      summary: Get metadata associated with an authorisation domain role
      tags:
        - Reference Data
        - Authorisation Domain Role Metadata
        - Public
        - Closed
      security:
        - oAuth:
          - directory:software
          - directory:website
      
    put:
      summary: Change the status of a metadata object that is associated with an authorisation domain role
      tags:
        - Reference Data
        - Authorisation Domain Role Metadata
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete a metadata object that is associated with an authorisation domain role
      tags:
        - Reference Data
        - Authorisation Domain Role Metadata
        - Public
        - Deprecated
      security:
        - oAuth:
          - directory:website
      
  '/references/authorisationdomains':
    get:
      summary: Reference data of all authorisation domains
      tags:
        - Reference Data
        - Authorisation Domains
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create an authorisation domain
      tags:
        - Reference Data
        - Authorisation Domains
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorisationdomains/{AuthorisationDomainName}':
    get:
      summary: Get an authorisation domain by Name
      tags:
        - Reference Data
        - Authorisation Domains
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update an authorisation domain by Name
      tags:
        - Reference Data
        - Authorisation Domains
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorities':
    get:
      summary: Reference Data of all authorities
      tags:
        - Reference Data
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create a reference authority
      tags:
        - Reference Data
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorities/{AuthorityId}':
    get:
      summary: Get a reference authority by Id
      tags:
        - Reference Data
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update a reference authority by Id
      tags:
        - Reference Data
        - Authorities
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorities/{AuthorityId}/authorisationdomains':
    get:
      summary: Reference data of all authorisation domains for an Authority ID
      tags:
        - Reference Data
        - Authorisation Domains
        - Authorities
        - Authority Domain Mappings
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Map an authorisation domain to an authority
      tags:
        - Reference Data
        - Authorisation Domains
        - Authorities
        - Authority Domain Mappings
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authorities/{AuthorityId}/authorisationdomains/{AuthorityAuthorisationDomainId}':
    get:
      summary: Get an authority authorisation domain by Id
      tags:
        - Reference Data
        - Authorisation Domains
        - Authorities
        - Authority Domain Mappings
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Activate an authority authorisation domain by Id
      tags:
        - Reference Data
        - Authorisation Domains
        - Authorities
        - Authority Domain Mappings
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Deactivate an authority authorisation domain by Id
      tags:
        - Reference Data
        - Authorisation Domains
        - Authorities
        - Authority Domain Mappings
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/references/authoritydomainmapping':
    get:
      summary: Mappings of authorities with authorisation domains
      tags:
        - Reference Data
        - Authorisation Domains
        - Authorities
        - Authority Domain Mappings
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
          - directory:software
      
  '/references/certificationtypes':
    get:
      summary: Get certification types
      tags:
        - Reference Data
        - Certification Type
        - Public
      security:
        - oAuth:
          - directory:website
      
    post:
      summary: Set certification types
      tags:
        - Reference Data
        - Certification Type
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/certificationtypes/{TypeID}':
    get:
      summary: Get a specific certification type by ID
      tags:
        - Reference Data
        - Certification Type
        - Public
      security:
        - oAuth:
          - directory:website
      
    put:
      summary: Update certification types
      tags:
        - Reference Data
        - Certification Type
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete a certification type
      tags:
        - Reference Data
        - Certification Type
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/certificationtypes/{TypeID}/variants':
    get:
      summary: Get certification type variants
      tags:
        - Reference Data
        - Certification Type
        - Certification Type Variant
        - Public
      security:
        - oAuth:
          - directory:website
      
    post:
      summary: Set certification type variant
      tags:
        - Reference Data
        - Certification Type
        - Certification Type Variant
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/certificationtypes/{TypeID}/variants/{VariantID}':
    get:
      summary: Get certification type variant by ID
      tags:
        - Reference Data
        - Certification Type
        - Certification Type Variant
        - Public
      security:
        - oAuth:
          - directory:website
      
    put:
      summary: Update certification type variant by ID
      tags:
        - Reference Data
        - Certification Type
        - Certification Type Variant
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete a certification type variant
      tags:
        - Reference Data
        - Certification Type
        - Certification Type Variant
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/federations':
    get:
      summary: Get all federations
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create a new federation
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/federations/{FederationId}':
    get:
      summary: Get a federation by id
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update a federation
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete a federation
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/federations/{FederationId}/metadata-policy':
    get:
      summary: Get the metadata policy for a federation
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create a new metadata policy
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/federations/{FederationId}/metadata-policy/{MetadataPolicyId}':
    get:
      summary: Get a metadata policy
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update a metadata policy
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete a metadata policy
      tags:
        - Reference Data
        - Federation
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/flags':
    get:
      summary: Returns all flags configured at a reference data level
      tags:
        - Reference Data
        - Flags
        - Public
      security:
        - oAuth:
          - directory:website
      
    post:
      summary: Create a new flag
      tags:
        - Reference Data
        - Flags
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/flags/{FlagID}':
    get:
      summary: Returns a specific flag configured at a reference data level
      tags:
        - Reference Data
        - Flags
        - Public
      security:
        - oAuth:
          - directory:website
      
    put:
      summary: Updates an existing flag
      tags:
        - Reference Data
        - Flags
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Delete an existing flag
      tags:
        - Reference Data
        - Flags
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/organisationLabels':
    get:
      summary: Reference Data of all organisation labels
      tags:
        - Reference Data
        - Organisation Label
        - Public
      security:
        - oAuth:
          - directory:website
      
    post:
      summary: Create an organisation label
      tags:
        - Reference Data
        - Organisation Label
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/organisationLabels/{OrganisationLabelId}':
    get:
      summary: Get a reference organisation label by Id
      tags:
        - Reference Data
        - Organisation Label
        - Public
      security:
        - oAuth:
          - directory:website
      
    put:
      summary: Update a reference organisation label by Id
      tags:
        - Reference Data
        - Authorities
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/termsandconditions':
    get:
      summary: All terms and conditions
      tags:
        - Reference Data
        - Terms and Conditions
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create TnC
      tags:
        - Reference Data
        - Terms and Conditions
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/termsandconditions/{TnCId}':
    get:
      summary: Get details for a TnC document
      tags:
        - Reference Data
        - Terms and Conditions
        - Public
      security:
        - oAuth:
          - directory:website
      
    put:
      summary: Update the content of a TnC document
      tags:
        - Reference Data
        - Terms and Conditions
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Deactivate a TnC document
      tags:
        - Reference Data
        - Terms and Conditions
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/users/authorisationdomain/systems':
    get:
      summary: Reference Data of all authorisation domain systems
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create Reference Data for a new authorisation domain system
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/users/authorisationdomain/systems/{AuthorisationDomainSystemID}':
    get:
      summary: Get specific record for authorisation domain system
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update Reference Data for a new authorisation domain system
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Remove Reference Data for a new authorisation domain system
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/users/authorisationdomain/usertypes':
    get:
      summary: Reference Data of all authorisation domain user types
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    post:
      summary: Create Reference Data for a new authorisation domain user type
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/references/users/authorisationdomain/usertypes/{AuthorisationDomainUserTypeID}':
    get:
      summary: Get specific record for authorisation domain user type
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
          - directory:software
      
    put:
      summary: Update Reference Data for a new authorisation domain user type
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
    delete:
      summary: Remove Reference Data for a new authorisation domain user type
      tags:
        - Reference Data
        - Authorisation Domains
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/users':
    post:
      summary: User create API
      tags:
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/users/super':
    get:
      summary: All super users
      tags:
        - Users
        - Super Users
        - Public
      security:
        - oAuth:
          - directory:admin
          - directory:website
      
  '/users/{UserEmailId}':
    get:
      summary: Details of the user
      tags:
        - Users
        - Public
        - Closed
      security:
        - oAuth:
          - directory:website
      
  '/users/{UserEmailId}/history':
    get:
      summary: TnC history of the user
      tags:
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
  '/users/{UserEmailId}/{TnCId}':
    put:
      summary: API for capturing the updated Directory TnC ID agreed by the user
      tags:
        - Users
        - Public
      security:
        - oAuth:
          - directory:website
      
components:
    securitySchemes:
        oAuth:
            description: This API uses OAUTH 2.0 with client creds for the admin role and auth code for web users
            flows:
                authorizationCode:
                    authorizationUrl: https://auth.openbanking.raidiam.io/auth
                    refreshUrl: https://auth.openbanking.raidiam.io/token
                    scopes:
                        directory:website: Web based operations
                    tokenUrl: https://auth.openbanking.raidiam.io/token
                clientCredentials:
                    scopes:
                        directory:admin: All operations for super and domain users
                        directory:software: Software statement client operations
                    tokenUrl: https://auth.openbanking.raidiam.io/token
            type: oauth2