ruby '>= 2.5'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.5.0'
gem 'nokogiri', '~> 1.12.1'
gem 'sass'
gem 'webrick'
gem 'rack', '~> 2.2.3.1' # Atualização corrigindo vulnerabilidade Possible shell escape sequence injection vulnerability in Rack